services:
  db:
    image: postgres:17
    container_name: url-shortener-postgres-compose
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres-password
      POSTGRES_DB: urlshortener
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - jesusvale
  redis-cache:
    image: redis:7
    container_name: redis-url-shortener-compose
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data
    networks:
      - jesusvale
  url-shortener:
    image: jesusvale/url-shortener-service:1.0.0
    container_name: url-shortener-service
    ports:
      - 8081:8081
    environment:
      SPRING_APPLICATION_NAME: url-shortener-service
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/urlshortener
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres-password
      SPRING_REDIS_HOST: redis-cache
      SPRING_REDIS_PORT: 6379
    networks:
      - jesusvale
    deploy:
      resources:
        limits:
          memory: 700m
    depends_on:
      db:
        condition: service_healthy
      redis-cache:
        condition: service_healthy

volumes:
  db_data:
  redis_data:

networks:
  jesusvale:
    driver: bridge
