version: "3.9"

services:
  db:
    image: postgres:17
    container_name: url-shortener-postgres-compose
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres-password
      POSTGRES_DB: urlshortener
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:8
    container_name: redis-url-shortener-compose
    ports:
      - 6379:6379

volumes:
  db_data:
  redis_data: