spring:
  application:
    name: url-shortener-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # options: validate, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis
  redis:
    host: ${SPRING_REDIS_HOST:redis-cache}
    port: ${SPRING_REDIS_PORT:6379}
    timeout: 60000
    lettuce:
      shutdown-timeout: 100
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1000

logging:
  level:
    org.springframework.data.redis: DEBUG
    io:
      lettuce:
        core: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*" #Enable all endpoints of the actuator
  endpoint:
    health:
      show-details: always
      redis:
        enabled: false

server:
  port: 8081
